---
title: "Assignment2"
{r}
author: "Zijun Lin"
date: "2020/11/22"
output: html_document
---


2.(b)
```{r}
load("dataex2.Rdata")
load("dataex4.Rdata")
load("dataex5.Rdata")
require(maxLik)
```

```{r, include = TRUE, message = FALSE}
sigma = 1.5

#get the loglikelihood
log_like <- function(data, mu){
  x = dataex2$X
  r = dataex2$R
  p = dnorm(x, mean = mu, sd = sigma)
  
  sum(r*log(dnorm(x, mean = mu, sd = sigma))+(1-r)*log(qnorm(p, mean = mu, sd = sigma)))
}

mle <- maxLik(logLik = log_like, data = dataex2, start = c(10))
summary(mle)
```
mu = 5.914

4.
```{r}
em.bernoulli <- function(y, theta0, eps){
  theta <- theta0
  beta0 <- theta[1]
  beta1 <- theta[2]
  
  # observed data and missing data
  x_obs <- dataex4$X[is.na(dataex4$Y) == FALSE]
  x_mis <- dataex4$x[is.na(dataex4$Y) == TRUE]
  
  n <- length(x_obs)
  
  diff <- 1
  
  while(diff>eps){
    theta.old <- theta
    
    #E-step
    ptilde <- (exp(beta0+x_mis*beta1))/(1+exp(beta0+x_obs*beta1))
    
    #M-step
    
    
    diff <- sum(abs(theta - theta.old))
  }
  
  
}
```


5.
```{r, include = TRUE, message = FALSE}
# EM algorithm 
em.mixture <- function(y, theta0, eps){
  n <- length(y)
  
  theta <- theta0
  
  p <- theta[1]
  mu <- theta[2]
  sigma <- theta[3]
  lambda <- theta[4]
  
  diff <- 1
  while(diff > eps){
    theta.old <- theta
    
    #E-step
    ptilde1 <- p*dlnorm(y, mean = mu, sd = sigma)
    ptilde2 <- (1 - p)*dexp(y, rate = lambda)
    ptilde <- ptilde1/(ptilde1 + ptilde2)
    
    #M-step
    p <- mean(ptilde)
    mu <- sum(ptilde*log(y))/sum(ptilde)
    sigma <- sqrt(sum(ptilde*(log(y)-mu)^2)/sum(ptilde))
    lambda <- sum(1-ptilde)/sum((1-ptilde)*y)
    
    theta <- c(p, mu, sigma, lambda)
    diff <- sum(abs(theta - theta.old))
  }
  return(theta)
}
```


```{r}
# get the estimated parameters
res <- em.mixture(y = dataex5, c(0.1, 1, 0.5, 2), 0.00001)
p <- res[1]
mu <- res[2]
sigma <- res[3]
lambda <- res[4]

p; mu; sigma; lambda
```

```{r}
# plot the histogram of data and the curve of the estimated density function
hist(y, main = "dataex5", 
     xlab = "y", ylab = "Density", cex.main = 1.1, 
     freq = F, ylim = c(0,0.2))
curve(p*dlnorm(x, mu, sigma) + (1 - p)*dexp(x, lambda), 
      add = TRUE, lwd = 1, col = "blue2")
```






